### ISSUE TITLE
测试时报错

### ISSUE THREAD

**Issue by CurryaNa** [HaochenLiu2000/SAFER#1]
你好，训练时可以正常训练，但是测试时报了这个错，这是什么原因呢：
  0%|                                                                                                         | 0/2125 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/xuyiming/Few-shot/Edge-level/SAFER/main.py", line 34, in <module>
    data = trainer.model2(test_data_loader_ranktail4, istest=True)
  File "/data/xuyiming/Few-shot/Edge-level/SAFER/trainer.py", line 149, in model2
    query_ans_list, negative_ans_list, query_sim_train, negative_sim_train = self.model2_ex(eval_task, iseval=False, is_eval_loss = True , curr_rel=curr_rel, trial = trial, best_params = best_params)
  File "/data/xuyiming/Conda/anaconda3/envs/enmark/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/xuyiming/Conda/anaconda3/envs/enmark/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xuyiming/Few-shot/Edge-level/SAFER/models.py", line 470, in forward
    _, loss, edgemask1 = self.weight.embedding_learner.get_masked_graph_embedding(support_subgraphs_mix, graph_emb_permute, size_loss_beta = 0)
  File "/data/xuyiming/Few-shot/Edge-level/SAFER/models.py", line 233, in get_masked_graph_embedding
    edgemask = self.gen_mask_gnn(graphs, prototype)
  File "/data/xuyiming/Few-shot/Edge-level/SAFER/models.py", line 210, in gen_mask_gnn
    _, _, edge_attr = self.egnn(graphs, extra_cond = prototype[edge_batch] )
  File "/data/xuyiming/Conda/anaconda3/envs/enmark/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/xuyiming/Conda/anaconda3/envs/enmark/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xuyiming/Few-shot/Edge-level/SAFER/RGCN.py", line 161, in forward
    batch_num_nodes = scatter_sum(torch.ones(batch.shape).to(batch.device), batch)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by HaochenLiu2000** [comment]
Hi,

Could you provide more detailed info about the error?

**Comment by CurryaNa** [comment]
您好，就是训练完之后，然后运行测试命令：python main.py --use_atten True --use_pretrain_node_emb True --dataset NELL --device 0 --step model2 -prev_state_dir_model2 NELL/train_1/checkpoint.ckpt
然后加载数据集都正常，刚开始测试就报了这个错误：
use original emb TransE
loading pre-trained embedding...
loading into edge embedding...
use original emb TransE
loading pre-trained embedding...
loading into node embedding...
  0%|                                                                                                         | 0/2125 [00:00<?, ?
先是很多行的这个：  
it/s]../aten/src/ATen/native/cuda/Indexing.cu:1231: indexSelectSmallIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1231: indexSelectSmallIndex: block: [0,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1231: indexSelectSmallIndex: block: [0,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1231: indexSelectSmallIndex: block: [0,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1231: indexSelectSmallIndex: block: [0,0,0], thread: [4,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
然后是下边这个错误：
0%|                                                                                                         | 0/2125 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/xuyiming/Few-shot/Edge-level/SAFER/main.py", line 34, in <module>
    data = trainer.model2(test_data_loader_ranktail4, istest=True)
  File "/data/xuyiming/Few-shot/Edge-level/SAFER/trainer.py", line 149, in model2
    query_ans_list, negative_ans_list, query_sim_train, negative_sim_train = self.model2_ex(eval_task, iseval=False, is_eval_loss = True , curr_rel=curr_rel, trial = trial, best_params = best_params)
  File "/data/xuyiming/Conda/anaconda3/envs/enmark/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/xuyiming/Conda/anaconda3/envs/enmark/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xuyiming/Few-shot/Edge-level/SAFER/models.py", line 470, in forward
    _, loss, edgemask1 = self.weight.embedding_learner.get_masked_graph_embedding(support_subgraphs_mix, graph_emb_permute, size_loss_beta = 0)  
  File "/data/xuyiming/Few-shot/Edge-level/SAFER/models.py", line 233, in get_masked_graph_embedding
    edgemask = self.gen_mask_gnn(graphs, prototype)
  File "/data/xuyiming/Few-shot/Edge-level/SAFER/models.py", line 210, in gen_mask_gnn
    _, _, edge_attr = self.egnn(graphs, extra_cond = prototype[edge_batch] )
  File "/data/xuyiming/Conda/anaconda3/envs/enmark/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/xuyiming/Conda/anaconda3/envs/enmark/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xuyiming/Few-shot/Edge-level/SAFER/RGCN.py", line 161, in forward
    batch_num_nodes = scatter_sum(torch.ones(batch.shape).to(batch.device), batch)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
代码没有修改，请问是什么问题呢？在网上搜是说这个错误通常是由于GPU设备在执行过程中发生断言失败，引发了程序崩溃。

**Comment by Linawdjn** [comment]
+1

**Comment by CurryaNa** [comment]
问题就出在这里：
models.py的466行
graph_emb_permute = torch.index_select(graph_emb_permute, 0, torch.LongTensor([1, 2, 0]).to(graph_emb_permute.device))
我尝试打印graph_emb_permute的shape,发现是torch.Size([2, 584])
也就是说第一个维度不符合，参数里设置的few一开始3，但是few=len(support_subgraphs)这里得到的是2.
请您解答一下。

**Comment by DuanyangYuan** [comment]
> 问题就出在这里： models.py的466行 graph_emb_permute = torch.index_select(graph_emb_permute, 0, torch.LongTensor([1, 2, 0]).to(graph_emb_permute.device)) 我尝试打印graph_emb_permute的shape,发现是torch.Size([2, 584]) 也就是说第一个维度不符合，参数里设置的few一开始3，但是few=len(support_subgraphs)这里得到的是2. 请您解答一下。

您好，请问您解决了吗

**Comment by HaochenLiu2000** [comment]
Hi all, we have corrected the mistake of "few=2" in the evaluation part. We mistakenly retained some codes for the case study there, and we have revised them.
